drop table if exists games;

create table games (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    publisher TEXT NOT NULL
);

INSERT into games (title, publisher)
values
    ('Warcraft III', 'Blizzard'),
    ('Starcraft II', 'Blizzard'); 

